import type { NextPage } from 'next';
import Head from 'next/head';
import Hero from '../components/Hero';
import RoutesHistory from '../components/RoutesHistory';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Recruit Task</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<div className="w-min mx-auto">
				<RoutesHistory />
			</div>
		</div>
	);
};

export default Home;
