import type { NextPage } from 'next';
import Head from 'next/head';
import Navigation from '../components/Navigation';

const NavigationPage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Navigation</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navigation />
		</div>
	);
};

export default NavigationPage;
