import type { NextPage } from 'next';
import Head from 'next/head';
import dynamic from 'next/dynamic';

const Route = dynamic(() => import('../components/Route'), {
	ssr: false,
});

const RoutePage: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Route</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Route />
		</div>
	);
};

export default RoutePage;
